"""Software pipeline framework for PyTorch / CUDA.

Overlaps tasks from different loop iterations across CUDA streams and
CPU threads.  Usage::

    plan = PipelinePlan(schedule={...}, deps=[...], pipeline_depth=3)
    pipe = SWPipeline(plan, device=0)
    pipe.fill_pipeline(data_iter)
    while True:
        try:
            pipe.progress(data_iter)
        except StopIteration:
            break
"""

from __future__ import annotations

import bisect
import contextlib
import queue as queue_module
import threading
import time
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, Iterator, List, Optional, Tuple, Union

import torch
import torch.cuda

try:
    import nvtx as _nvtx

    _nvtx_range_start = _nvtx.start_range
    _nvtx_range_end = _nvtx.end_range
except ImportError:

    def _nvtx_range_start(msg: str) -> object:  # type: ignore[misc]
        return None

    def _nvtx_range_end(handle: object) -> None:  # type: ignore[misc]
        pass


_nullcontext = contextlib.nullcontext


class IterContext:
    """Per-iteration state passed to every task function.

    ``batch`` holds the raw data; tasks attach intermediates as attributes
    (e.g. ``ctx.emb = …``).  Each in-flight iteration gets its own context
    to avoid cross-iteration data hazards.
    """

    def __init__(self, batch: Any, iter_idx: int) -> None:
        self.batch = batch
        self.iter_idx = iter_idx


class _SubmissionSequencer:
    """Serialize task submission in a deterministic order across threads.

    Each ``globally_ordered`` task gets a pre-assigned sequence number.
    ``execute_ordered`` blocks until it is that task's turn, ensuring
    identical call order across ranks regardless of OS thread scheduling.
    """

    def __init__(self) -> None:
        self._next_seq: int = 0
        self._cond = threading.Condition(threading.Lock())

    def reset(self) -> None:
        with self._cond:
            self._next_seq = 0

    def execute_ordered(self, seq: int, fn: Callable[[], None]) -> None:
        with self._cond:
            if not self._cond.wait_for(lambda: self._next_seq == seq, timeout=30):
                raise RuntimeError(
                    f"Sequencer timed out: waiting for seq={seq}, "
                    f"current _next_seq={self._next_seq}"
                )
            fn()
            self._next_seq += 1
            self._cond.notify_all()


@dataclass(eq=False)
class PipelineTask:
    """One schedulable unit inside an iteration.

    ``fn(ctx)`` receives the ``IterContext`` for the current iteration,
    reads inputs from ``ctx.*``, writes outputs back, and optionally
    ``del``s consumed attributes to free memory early.

    ``PipelineTask`` only declares the computation identity (name + fn).
    Scheduling properties (stage, stream, thread_group, dependencies) are
    specified in ``PipelinePlan``, analogous to how TorchRec separates
    ``EmbeddingBagConfig`` from ``ShardingPlan``.
    """

    name: str
    fn: Callable[["IterContext"], None]

    def __hash__(self) -> int:
        return hash(self.name)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, PipelineTask):
            return NotImplemented
        return self.name == other.name


TaskRef = Union[str, PipelineTask]
"""Anywhere a task is referenced by name, a ``PipelineTask`` object is also accepted."""


def _resolve(ref: TaskRef) -> str:
    return ref.name if isinstance(ref, PipelineTask) else ref


@dataclass
class TaskSchedule:
    """Per-task scheduling configuration within a ``PipelinePlan``."""

    stage: int = 0
    stream: Optional[torch.cuda.Stream] = None
    thread_group: str = "default"
    globally_ordered: bool = False


@dataclass
class PipelinePlan:
    """Complete scheduling plan for a software pipeline.

    Analogous to TorchRec's ``ShardingPlan``: separates *what* to compute
    (``PipelineTask``) from *how* to schedule it.  A plan can be
    constructed manually or generated by an auto-scheduling algorithm.

    ``schedule`` keys define the task set — no separate ``tasks`` parameter
    is needed.  Both ``PipelineTask`` objects and name strings are accepted
    as keys and in dependency tuples (``TaskRef``).
    """

    schedule: Dict[TaskRef, TaskSchedule]
    deps: List[Tuple[TaskRef, TaskRef]]
    cross_iter_deps: List[Tuple[TaskRef, TaskRef]] = field(default_factory=list)
    pipeline_depth: int = 2


_SENTINEL = None


class SWPipeline:
    """General-purpose software pipeline for CUDA / PyTorch workloads.

    Args:
        plan: A ``PipelinePlan`` that specifies tasks, scheduling, and deps.
        device: CUDA device ordinal.

    Execution model — each *period* submits every task once::

        iter_idx = period - stage_map[task]

    Negative or out-of-range ``iter_idx`` → skip (prologue / epilogue).

    Synchronization uses a two-phase protocol per dependency:
    CPU ``threading.Event`` ensures the CUDA event is recorded before
    ``stream.wait_event`` is called (prevents wait-before-record pitfall).
    """

    def __init__(self, plan: PipelinePlan, device: int = 0) -> None:
        self.device = device
        self.depth = plan.pipeline_depth

        self._defs: Dict[str, PipelineTask] = {}
        self._stage_map: Dict[str, int] = {}
        self._stream_map: Dict[str, Optional[torch.cuda.Stream]] = {}
        self._thread_group_map: Dict[str, str] = {}
        self._globally_ordered: Dict[str, bool] = {}

        for ref, sched in plan.schedule.items():
            task = ref if isinstance(ref, PipelineTask) else None
            name = _resolve(ref)
            if task is None:
                raise ValueError(
                    f"schedule key '{name}' is a string; "
                    f"PipelineTask objects are required as keys"
                )
            if name in self._defs:
                raise ValueError(f"duplicate task name: {name}")
            self._defs[name] = task
            self._stage_map[name] = sched.stage
            self._stream_map[name] = sched.stream
            self._thread_group_map[name] = sched.thread_group
            self._globally_ordered[name] = sched.globally_ordered

        self._deps: Dict[str, List[str]] = defaultdict(list)
        for task_ref, dep_ref in plan.deps:
            self._deps[_resolve(task_ref)].append(_resolve(dep_ref))

        self._cross_iter_deps: Dict[str, List[str]] = defaultdict(list)
        for task_ref, dep_ref in plan.cross_iter_deps:
            self._cross_iter_deps[_resolve(task_ref)].append(_resolve(dep_ref))

        self._validate()

        self._default_stream = torch.cuda.current_stream(device)
        self._max_stage = max(self._stage_map.values()) if self._stage_map else 0
        self._num_tasks = len(self._defs)
        self._topo_order: List[PipelineTask] = self._topo_sort()
        self._enqueue_order: List[PipelineTask] = self._build_enqueue_order()
        self._sequencer = _SubmissionSequencer()

        # Pre-allocated sync resources (slot = iter_idx % depth)
        self._cuda_events: Dict[Tuple[int, str], torch.cuda.Event] = {}
        self._cpu_signals: Dict[Tuple[int, str], threading.Event] = {}
        self._iter_complete: List[threading.Event] = []
        self._iter_tasks_remaining: List[int] = []
        for slot in range(self.depth):
            self._iter_complete.append(threading.Event())
            self._iter_tasks_remaining.append(0)
            for task_name in self._defs:
                self._cuda_events[(slot, task_name)] = torch.cuda.Event()
                self._cpu_signals[(slot, task_name)] = threading.Event()

        # Cross-iteration dependency signals keyed by absolute iter_idx
        # (not slot) so they survive slot reuse from _reset_slot.
        self._cross_iter_cuda_events: Dict[Tuple[int, str], torch.cuda.Event] = {}
        self._cross_iter_cpu_signals: Dict[Tuple[int, str], threading.Event] = {}
        self._cross_iter_task_names: set = {
            dep_name
            for _, dep_list in self._cross_iter_deps.items()
            for dep_name in dep_list
        }

        # Mutable execution state (reset per run)
        self._pipeline_started: bool = False
        self._data_exhausted: bool = False
        self._current_period: int = 0
        self._next_retire: int = 0
        self._contexts: Dict[int, IterContext] = {}
        self._seq_map: Dict[Tuple[int, str], int] = {}
        self._next_seq: int = 0
        self._work_queues: Dict[str, queue_module.Queue] = {}
        self._worker_threads: List[threading.Thread] = []
        self._completion_lock = threading.Lock()
        self._worker_error: Optional[BaseException] = None
        self._worker_error_lock = threading.Lock()
        self._iter_nvtx_handles: Dict[int, object] = {}

        # Task shortcut support
        self._shortcut_tasks: set = set()
        self._shortcut_cache: Dict[str, Tuple[Dict[str, Any], frozenset]] = {}

    # -- shortcut API --

    def enable_shortcut(self, *task_names: str) -> None:
        """Enable shortcut mode for the given tasks.

        On the **first** execution after enabling, the task runs normally
        and its ``IterContext`` outputs are cached.  All subsequent
        executions skip ``fn(ctx)`` and replay cached outputs (with
        ``detach().clone().requires_grad_()`` to preserve the autograd
        graph for downstream tasks).

        For ``globally_ordered`` tasks the ``_SubmissionSequencer`` still
        fires (maintaining cross-rank order) — only the computation is
        skipped.

        All ranks must enable/disable the same tasks to avoid NCCL hangs.
        """
        valid = {t.name for t in self._topo_order}
        for n in task_names:
            if n not in valid:
                raise ValueError(f"Unknown task: {n!r}")
            self._shortcut_tasks.add(n)

    def disable_shortcut(self, *task_names: str) -> None:
        """Disable shortcut mode and clear the cache for the given tasks."""
        for n in task_names:
            self._shortcut_tasks.discard(n)
            self._shortcut_cache.pop(n, None)

    # -- shortcut internals --

    @staticmethod
    def _cache_val(v: Any) -> Any:
        """Cache a value.  For tensors, store ``(detached_clone, requires_grad)``."""
        if isinstance(v, torch.Tensor):
            return (v.detach().clone(), v.requires_grad)
        return v

    @staticmethod
    def _restore_val(v: Any) -> Any:
        """Restore a cached value.  Zero-copy for tensors (``detach()``,
        no D2D memcpy), faithfully restoring the original ``requires_grad``
        state.

        Trade-off: downstream tasks must NOT modify shortcut outputs
        in-place (e.g. ``tensor.add_(...)``), as that would corrupt the
        shared cache storage.
        """
        if isinstance(v, tuple) and len(v) == 2 and isinstance(v[0], torch.Tensor):
            tensor, grad = v
            t = tensor.detach()
            if grad:
                t.requires_grad_(True)
            return t
        return v

    def _apply_shortcut(self, ctx: IterContext, name: str) -> None:
        """Replay cached outputs onto *ctx*."""
        produced, deleted = self._shortcut_cache[name]
        for k in deleted:
            if hasattr(ctx, k):
                delattr(ctx, k)
        for k, v in produced.items():
            setattr(ctx, k, self._restore_val(v))

    def _capture_and_cache(
        self,
        ctx: IterContext,
        name: str,
        before_ids: Dict[str, int],
    ) -> None:
        """Snapshot new/changed attrs on *ctx* into the shortcut cache."""
        after = vars(ctx)
        produced = {
            k: self._cache_val(v)
            for k, v in after.items()
            if k not in before_ids or id(v) != before_ids[k]
        }
        deleted = frozenset(set(before_ids) - set(after))
        self._shortcut_cache[name] = (produced, deleted)

    def _exec_task(self, task_def: PipelineTask, ctx: IterContext) -> None:
        """Execute *task_def* on *ctx* with shortcut/caching support.

        Three modes:
        1. **Shortcut active** (name in ``_shortcut_tasks`` AND cache exists):
           skip ``fn(ctx)``, replay cached outputs.
        2. **Caching** (name in ``_shortcut_tasks`` but no cache yet):
           run ``fn(ctx)`` normally, capture outputs into cache.
        3. **Normal** (name not in ``_shortcut_tasks``):
           run ``fn(ctx)`` with zero overhead.
        """
        name = task_def.name
        if name in self._shortcut_tasks:
            if name in self._shortcut_cache:
                self._apply_shortcut(ctx, name)
                return
            before_ids = {k: id(v) for k, v in vars(ctx).items()}
            task_def.fn(ctx)
            self._capture_and_cache(ctx, name, before_ids)
            return
        task_def.fn(ctx)

    # -- helpers --

    def _slot(self, iter_idx: int) -> int:
        return iter_idx % self.depth

    def _cuda_event(self, iter_idx: int, task_name: str) -> torch.cuda.Event:
        return self._cuda_events[(self._slot(iter_idx), task_name)]

    def _cpu_signal(self, iter_idx: int, task_name: str) -> threading.Event:
        return self._cpu_signals[(self._slot(iter_idx), task_name)]

    def _reset_slot(self, slot: int) -> None:
        self._iter_complete[slot].clear()
        self._iter_tasks_remaining[slot] = self._num_tasks
        for task_name in self._defs:
            self._cpu_signals[(slot, task_name)].clear()

    # -- validation --

    def _validate(self) -> None:
        all_names = set(self._defs)
        max_stage = max(self._stage_map.values()) if self._stage_map else 0
        for task_name, dep_list in self._deps.items():
            if task_name not in all_names:
                raise ValueError(f"deps: unknown task '{task_name}'")
            for dep_name in dep_list:
                if dep_name not in all_names:
                    raise ValueError(f"unknown dependency '{dep_name}' for {task_name}")
        for task_name, dep_list in self._cross_iter_deps.items():
            if task_name not in all_names:
                raise ValueError(f"cross_iter_deps: unknown task '{task_name}'")
            for dep_name in dep_list:
                if dep_name not in all_names:
                    raise ValueError(
                        f"unknown cross-iter dep '{dep_name}' for {task_name}"
                    )
        if self.depth < max_stage + 1:
            raise ValueError(
                f"pipeline_depth {self.depth} < max(stage)+1 = {max_stage + 1}"
            )
        self._validate_no_hol_deadlock()

    def _validate_no_hol_deadlock(self) -> None:
        """Warn about potential head-of-line blocking.

        Pattern: task A (stage S_a) has a cross-iter dep and shares a
        thread group with task B (stage S_b > S_a).  When A blocks on its
        cross-iter wait, B is stuck behind A in the FIFO queue, which can
        starve pipeline progress.

        The stage-descending enqueue order (``_enqueue_order``) mitigates
        most common cases by ensuring higher-stage tasks are queued before
        lower-stage ones within each period.  However, cross-period
        queueing can still cause temporary stalls, so we emit a warning.
        """
        import warnings

        group_tasks: Dict[str, List[str]] = defaultdict(list)
        for name, group in self._thread_group_map.items():
            group_tasks[group].append(name)

        for group, task_names in group_tasks.items():
            stages = {n: self._stage_map[n] for n in task_names}
            max_stg = max(stages.values())
            for name in task_names:
                if name not in self._cross_iter_deps or stages[name] >= max_stg:
                    continue
                higher = [n for n in task_names if stages[n] > stages[name]]
                warnings.warn(
                    f"Potential head-of-line blocking: '{name}' "
                    f"(stage {stages[name]}) has cross-iteration "
                    f"dependencies and shares thread group '{group}' "
                    f"with higher-stage task(s) {higher}. Consider "
                    f"assigning them to separate thread groups.",
                    stacklevel=2,
                )

    def _build_enqueue_order(self) -> List[PipelineTask]:
        """Stage-descending enqueue order: older iterations first.

        Within each period, tasks are enqueued highest-stage first so
        that tasks closer to completing their iteration get into the
        work queue ahead of newer-iteration tasks that may block on
        cross-iteration dependencies.  This prevents the common
        head-of-line blocking pattern where a stage-0 task blocks the
        queue and starves a stage-1+ task needed for pipeline progress.

        Within each stage the original topological order is preserved.
        """
        order: List[PipelineTask] = []
        for stage in range(self._max_stage, -1, -1):
            order.extend(
                t for t in self._topo_order if self._stage_map[t.name] == stage
            )
        return order

    # -- topological sort --

    def _topo_sort(self) -> List[PipelineTask]:
        """Sort tasks by stage ascending, then by dependency order within stage.

        Ties broken by name for determinism (needed for globally_ordered
        sequence numbers to agree across ranks).
        """
        tasks_by_stage: Dict[int, List[PipelineTask]] = defaultdict(list)
        for task in self._defs.values():
            tasks_by_stage[self._stage_map[task.name]].append(task)

        result: List[PipelineTask] = []
        for stage in sorted(tasks_by_stage):
            group = tasks_by_stage[stage]
            group_names = {t.name for t in group}

            in_degree: Dict[str, int] = {t.name: 0 for t in group}
            adj: Dict[str, List[str]] = defaultdict(list)
            for task in group:
                for dep_name in self._deps.get(task.name, []):
                    if dep_name in group_names:
                        in_degree[task.name] += 1
                        adj[dep_name].append(task.name)

            by_name = {t.name: t for t in group}
            ready = sorted(n for n, d in in_degree.items() if d == 0)
            ordered: List[str] = []
            while ready:
                name = ready.pop(0)
                ordered.append(name)
                for succ in sorted(adj.get(name, [])):
                    in_degree[succ] -= 1
                    if in_degree[succ] == 0:
                        ready.append(succ)
                        ready.sort()

            if len(ordered) != len(group):
                raise ValueError(
                    f"dependency cycle in stage {stage}: "
                    f"{group_names - set(ordered)}"
                )
            result.extend(by_name[n] for n in ordered)

        return result

    # -- worker threads --

    def _start_workers(self) -> None:
        thread_groups = sorted(set(self._thread_group_map.values()))
        for group in thread_groups:
            work_queue: queue_module.Queue = queue_module.Queue()
            self._work_queues[group] = work_queue
            worker = threading.Thread(
                target=self._worker_loop,
                args=(work_queue,),
                daemon=True,
            )
            self._worker_threads.append(worker)
            worker.start()

    def _stop_workers(self) -> None:
        for work_queue in self._work_queues.values():
            work_queue.put(_SENTINEL)
        for worker in self._worker_threads:
            worker.join()
        self._worker_threads.clear()
        self._work_queues.clear()

    def _worker_loop(self, work_queue: queue_module.Queue) -> None:
        torch.cuda.set_device(self.device)
        while True:
            item = work_queue.get()
            if item is _SENTINEL:
                break
            iter_idx, task_def = item
            try:
                self._submit_task(iter_idx, task_def)
            except BaseException as exc:
                import sys
                import traceback

                traceback.print_exc(file=sys.stderr)
                with self._worker_error_lock:
                    if self._worker_error is None:
                        self._worker_error = exc
                slot = self._slot(iter_idx)
                with self._completion_lock:
                    self._iter_complete[slot].set()
                break

    def _submit_task(self, iter_idx: int, task_def: PipelineTask) -> None:
        ctx = self._contexts[iter_idx]
        stream = self._stream_map[task_def.name] or self._default_stream
        thread_name = threading.current_thread().name

        for dep_name in self._deps.get(task_def.name, []):
            sig = self._cpu_signal(iter_idx, dep_name)
            if not sig.wait(timeout=30):
                raise RuntimeError(
                    f"[{thread_name}] {task_def.name}(iter {iter_idx}): "
                    f"timed out waiting 30s for dep '{dep_name}' (iter {iter_idx})"
                )
            stream.wait_event(self._cuda_event(iter_idx, dep_name))

        if iter_idx > 0:
            for dep_name in self._cross_iter_deps.get(task_def.name, []):
                prev = iter_idx - 1
                key = (prev, dep_name)
                sig = self._cross_iter_cpu_signals.get(key)
                if sig is None:
                    raise RuntimeError(
                        f"[{thread_name}] {task_def.name}(iter {iter_idx}): "
                        f"cross-iter signal for '{dep_name}' (iter {prev}) "
                        f"was never created"
                    )
                if not sig.wait(timeout=30):
                    raise RuntimeError(
                        f"[{thread_name}] {task_def.name}(iter {iter_idx}): "
                        f"timed out waiting 30s for cross-iter dep "
                        f"'{dep_name}' (iter {prev})"
                    )
                stream.wait_event(self._cross_iter_cuda_events[key])

        is_skip = (
            task_def.name in self._shortcut_tasks
            and task_def.name in self._shortcut_cache
        )
        tag = f"SWP/{task_def.name}/iter{ctx.iter_idx}"
        if is_skip:
            tag += "[skip]"

        if self._globally_ordered[task_def.name]:
            seq = self._seq_map[(self._slot(iter_idx), task_def.name)]
            bound_stream, bound_task, bound_ctx = stream, task_def, ctx

            def _run_ordered() -> None:
                with torch.cuda.stream(bound_stream):
                    torch.cuda.nvtx.range_push(tag)
                    try:
                        self._exec_task(bound_task, bound_ctx)
                    finally:
                        torch.cuda.nvtx.range_pop()

            self._sequencer.execute_ordered(seq, _run_ordered)
        else:
            with torch.cuda.stream(stream):
                torch.cuda.nvtx.range_push(tag)
                try:
                    self._exec_task(task_def, ctx)
                finally:
                    torch.cuda.nvtx.range_pop()

        self._cuda_event(iter_idx, task_def.name).record(stream)
        self._cpu_signal(iter_idx, task_def.name).set()

        if task_def.name in self._cross_iter_task_names:
            key = (iter_idx, task_def.name)
            if key not in self._cross_iter_cuda_events:
                self._cross_iter_cuda_events[key] = torch.cuda.Event()
                self._cross_iter_cpu_signals[key] = threading.Event()
            self._cross_iter_cuda_events[key].record(stream)
            self._cross_iter_cpu_signals[key].set()

        slot = self._slot(iter_idx)
        with self._completion_lock:
            self._iter_tasks_remaining[slot] -= 1
            if self._iter_tasks_remaining[slot] == 0:
                handle = self._iter_nvtx_handles.pop(iter_idx, None)
                if handle is not None:
                    _nvtx_range_end(handle)
                self._iter_complete[slot].set()

    # -- period management --

    def _enqueue_period(self, period: int, data_iter: Optional[Iterator]) -> None:
        for task_def in self._enqueue_order:
            iter_idx = period - self._stage_map[task_def.name]
            if iter_idx < 0:
                continue

            if iter_idx not in self._contexts:
                if self._data_exhausted:
                    continue
                batch = next(data_iter, None) if data_iter is not None else None
                if batch is None:
                    self._data_exhausted = True
                    continue
                self._reset_slot(self._slot(iter_idx))
                self._contexts[iter_idx] = IterContext(batch, iter_idx)
                self._iter_nvtx_handles[iter_idx] = _nvtx_range_start(f"iter{iter_idx}")

            slot = self._slot(iter_idx)
            if self._globally_ordered[task_def.name]:
                self._seq_map[(slot, task_def.name)] = self._next_seq
                self._next_seq += 1

            if task_def.name in self._cross_iter_task_names:
                key = (iter_idx, task_def.name)
                if key not in self._cross_iter_cpu_signals:
                    self._cross_iter_cpu_signals[key] = threading.Event()
                    self._cross_iter_cuda_events[key] = torch.cuda.Event()

            self._work_queues[self._thread_group_map[task_def.name]].put(
                (iter_idx, task_def)
            )

    def _reset_state(self) -> None:
        self._pipeline_started = False
        self._data_exhausted = False
        self._current_period = 0
        self._next_retire = 0
        self._contexts.clear()
        self._seq_map.clear()
        self._next_seq = 0
        self._sequencer.reset()
        self._worker_error = None
        self._cross_iter_cuda_events.clear()
        self._cross_iter_cpu_signals.clear()
        for h in self._iter_nvtx_handles.values():
            if h is not None:
                _nvtx_range_end(h)
        self._iter_nvtx_handles.clear()
        for slot in range(self.depth):
            self._iter_complete[slot].clear()
            self._iter_tasks_remaining[slot] = 0
            for task_name in self._defs:
                self._cpu_signals[(slot, task_name)].clear()

    # -- public API --

    def fill_pipeline(self, data_iter) -> None:
        """Run prologue: prefetch ``depth`` batches and start workers.

        Must be called once before the first ``progress()`` call.
        Accepts any iterable (list, generator, iterator).
        Returns the iterator so callers can pass it to ``progress()``.
        """
        if self._pipeline_started:
            raise RuntimeError("fill_pipeline() already called")
        if not hasattr(data_iter, "__next__"):
            data_iter = iter(data_iter)
        self._reset_state()
        self._start_workers()
        for period in range(self.depth):
            self._enqueue_period(period, data_iter)
        self._current_period = self.depth
        self._pipeline_started = True
        return data_iter

    def progress(self, data_iter: Optional[Iterator] = None) -> int:
        """Advance one step: retire oldest iteration, enqueue next period.

        Returns the completed iteration index.
        Raises ``StopIteration`` when the pipeline is fully drained.
        """
        if not self._pipeline_started:
            raise RuntimeError("call fill_pipeline() before progress()")

        oldest = self._next_retire
        if oldest not in self._contexts:
            self._stop_workers()
            self._pipeline_started = False
            raise StopIteration

        torch.cuda.nvtx.range_push(f"SWP/retire{oldest}")
        slot = self._slot(oldest)
        if not self._iter_complete[slot].wait(timeout=60):
            remaining = self._iter_tasks_remaining[slot]
            pending = []
            for tname in self._defs:
                if not self._cpu_signals[(slot, tname)].is_set():
                    pending.append(tname)
            alive = {w.name: w.is_alive() for w in self._worker_threads}
            raise RuntimeError(
                f"Pipeline stalled: iter {oldest} (slot {slot}) did not "
                f"complete within 60s.\n"
                f"  tasks_remaining={remaining}/{self._num_tasks}\n"
                f"  pending tasks (cpu_signal not set): {pending}\n"
                f"  worker threads alive: {alive}"
            )
        with self._worker_error_lock:
            if self._worker_error is not None:
                err = self._worker_error
                self._worker_error = None
                self._stop_workers()
                self._pipeline_started = False
                raise RuntimeError(
                    f"Worker thread failed while processing pipeline"
                ) from err
        torch.cuda.current_stream(self.device).wait_event(
            self._cuda_event(oldest, self._topo_order[-1].name)
        )

        del self._contexts[oldest]
        stale = oldest - 1
        if stale >= 0:
            for tname in self._cross_iter_task_names:
                self._cross_iter_cuda_events.pop((stale, tname), None)
                self._cross_iter_cpu_signals.pop((stale, tname), None)
        self._next_retire += 1

        self._enqueue_period(self._current_period, data_iter)
        self._current_period += 1

        if not self._contexts and self._data_exhausted:
            self._stop_workers()

        torch.cuda.nvtx.range_pop()
        return oldest

    def run(
        self,
        data_iter: Iterator,
        verbose: bool = False,
        emit_nvtx: bool = False,
    ) -> float:
        """Run full pipeline, return wall-clock seconds.

        Args:
            emit_nvtx: wrap execution with ``torch.autograd.profiler.emit_nvtx()``
                so that backward-pass kernels (launched from autograd worker
                threads) get proper NVTX ranges visible in nsys GPU projection.
        """
        total = getattr(data_iter, "__len__", lambda: None)()
        data_iter = iter(data_iter)
        ctx_mgr = torch.autograd.profiler.emit_nvtx() if emit_nvtx else _nullcontext()
        torch.cuda.synchronize(self.device)
        start = time.perf_counter()
        with ctx_mgr:
            self.fill_pipeline(data_iter)
            completed = 0
            while True:
                try:
                    self.progress(data_iter)
                    completed += 1
                    if verbose:
                        self._print_progress("pipelined", completed, total, start)
                except StopIteration:
                    break
        if verbose:
            self._print_progress("pipelined", completed, total, start, finished=True)
        torch.cuda.synchronize(self.device)
        return time.perf_counter() - start

    def run_serial(
        self,
        data_iter: Iterator,
        verbose: bool = False,
        emit_nvtx: bool = False,
    ) -> float:
        """Run all iterations serially on default stream, return wall-clock seconds.

        Args:
            emit_nvtx: wrap execution with ``torch.autograd.profiler.emit_nvtx()``
                so that backward-pass kernels get proper NVTX ranges in nsys.
        """
        total = getattr(data_iter, "__len__", lambda: None)()
        ctx_mgr = torch.autograd.profiler.emit_nvtx() if emit_nvtx else _nullcontext()
        torch.cuda.synchronize(self.device)
        start = time.perf_counter()
        default_stream = torch.cuda.current_stream(self.device)
        with ctx_mgr:
            for idx, batch in enumerate(data_iter):
                ctx = IterContext(batch, idx)
                torch.cuda.nvtx.range_push(f"SWP_serial/iter{idx}")
                for task_def in self._topo_order:
                    is_skip = (
                        task_def.name in self._shortcut_tasks
                        and task_def.name in self._shortcut_cache
                    )
                    stag = f"SWP_serial/{task_def.name}/iter{ctx.iter_idx}"
                    if is_skip:
                        stag += "[skip]"
                    with torch.cuda.stream(default_stream):
                        torch.cuda.nvtx.range_push(stag)
                        try:
                            self._exec_task(task_def, ctx)
                        finally:
                            torch.cuda.nvtx.range_pop()
                torch.cuda.nvtx.range_pop()
                if verbose:
                    self._print_progress("serial", idx + 1, total, start)
        if verbose and "idx" in locals():
            self._print_progress("serial", idx + 1, total, start, finished=True)
        torch.cuda.synchronize(self.device)
        return time.perf_counter() - start

    @staticmethod
    def _print_progress(
        label: str,
        completed: int,
        total: Optional[int],
        start: float,
        *,
        finished: bool = False,
    ) -> None:
        import sys

        elapsed = time.perf_counter() - start
        rate = completed / elapsed if elapsed > 0 else 0.0
        if total is not None:
            pct = completed / total * 100
            eta = (total - completed) / rate if rate > 0 else 0.0
            msg = (
                f"\r[{label}] {completed}/{total} "
                f"({pct:5.1f}%) | {rate:.1f} it/s | "
                f"elapsed {elapsed:.1f}s | ETA {eta:.1f}s"
            )
        else:
            msg = (
                f"\r[{label}] {completed} iters | "
                f"{rate:.1f} it/s | elapsed {elapsed:.1f}s"
            )
        sys.stderr.write(msg)
        if finished:
            sys.stderr.write("\n")
        sys.stderr.flush()

    def run_one_serial_iter(self, batch: Any, iter_idx: int = 0) -> None:
        """Run a single serial iteration on the default stream.

        Respects ``enable_shortcut`` / ``disable_shortcut`` state — shortcut
        tasks will skip ``fn(ctx)`` and replay cached outputs.
        """
        ctx = IterContext(batch, iter_idx)
        stream = torch.cuda.current_stream(self.device)
        torch.cuda.nvtx.range_push(f"SWP_serial/iter{iter_idx}")
        for task_def in self._topo_order:
            is_skip = (
                task_def.name in self._shortcut_tasks
                and task_def.name in self._shortcut_cache
            )
            tag = f"SWP_serial/{task_def.name}/iter{iter_idx}"
            if is_skip:
                tag += "[skip]"
            with torch.cuda.stream(stream):
                torch.cuda.nvtx.range_push(tag)
                try:
                    self._exec_task(task_def, ctx)
                finally:
                    torch.cuda.nvtx.range_pop()
        torch.cuda.nvtx.range_pop()

    # -- debug / analysis --

    def print_stage_analysis(self) -> None:
        """Print topological schedule and Dilworth / LDS analysis."""
        topo_idx = {t.name: i for i, t in enumerate(self._topo_order)}
        stage_seq = [topo_idx[t.name] for t in self._topo_order]
        pipe_stg = [self._stage_map[t.name] for t in self._topo_order]

        print("Task schedule (topological order):")
        print(f"  {'Pos':>3}  {'Task':<16}  {'Idx':>4}  {'Stage':>5}  {'Type':<8}")
        print("  " + "-" * 50)
        for pos, task in enumerate(self._topo_order):
            kind = "ordered" if self._globally_ordered[task.name] else "stream"
            print(
                f"  {pos:>3}  {task.name:<16}  {topo_idx[task.name]:>4}"
                f"  {pipe_stg[pos]:>5}  {kind:<8}"
            )

        lds_len, lds_ex = self._compute_lds(stage_seq)
        print(f"\nSequence = {tuple(stage_seq)}")
        print(f"LDS = {lds_len}  (example: {tuple(lds_ex)})")
        print(f"Pipeline depth = {self.depth}")
        if lds_len == self.depth:
            print(f"  ✓  LDS == depth (Dilworth-optimal)")
        else:
            print(f"  ✗  LDS ({lds_len}) != depth ({self.depth})")

        print(f"\nStage decomposition ({len(set(pipe_stg))} groups):")
        for stg in sorted(set(pipe_stg)):
            names = [t.name for t in self._topo_order if self._stage_map[t.name] == stg]
            print(f"  stage {stg} (iter i-{stg}): {names}")

    @staticmethod
    def _compute_lds(seq: List[int]) -> Tuple[int, List[int]]:
        if not seq:
            return 0, []
        neg = [-v for v in seq]
        tails: List[int] = []
        tail_indices: List[int] = []
        predecessors = [-1] * len(neg)

        for i, val in enumerate(neg):
            idx = bisect.bisect_left(tails, val)
            if idx == len(tails):
                tails.append(val)
                tail_indices.append(i)
            else:
                tails[idx] = val
                tail_indices[idx] = i
            if idx > 0:
                predecessors[i] = tail_indices[idx - 1]

        witness: List[int] = []
        cur = tail_indices[-1]
        while cur != -1:
            witness.append(cur)
            cur = predecessors[cur]
        witness.reverse()
        return len(tails), [seq[i] for i in witness]

    def print_schedule(self, num_iterations: int) -> None:
        """Print the period × task schedule table."""
        total = num_iterations + self._max_stage
        header = f"{'Period':>6}"
        for task in self._topo_order:
            header += f"  {task.name:>14}"
        print(header)
        print("-" * len(header))
        for period in range(total):
            row = f"{period:>6}"
            for task in self._topo_order:
                idx = period - self._stage_map[task.name]
                cell = f"iter {idx}" if 0 <= idx < num_iterations else "---"
                row += f"  {cell:>14}"
            print(row)


# ================================================================== #
#  Task Profiler — exposed-time measurement for auto-scheduling
# ================================================================== #


@dataclass
class ProfileResult:
    """Result of :meth:`TaskProfiler.profile`.

    Attributes:
        baseline_s:  median wall-clock time of one serial iteration (seconds).
        exposed_s:   ``{task_name: exposed_seconds}`` — how much wall-clock
                     time is *removed* from the baseline when that task is
                     shortcut (replaced by cached results).
    """

    baseline_s: float
    exposed_s: Dict[str, float]

    def print_report(self) -> None:
        bms = self.baseline_s * 1e3
        print(f"Baseline serial iteration: {bms:.3f} ms\n")
        hdr = f"  {'Task':<24} {'Exposed':>10} {'% baseline':>12}"
        print(hdr)
        print(f"  {'-' * 24} {'-' * 10} {'-' * 12}")
        total = 0.0
        for name, t in self.exposed_s.items():
            ms = t * 1e3
            pct = t / self.baseline_s * 100 if self.baseline_s > 0 else 0
            total += t
            print(f"  {name:<24} {ms:>8.3f}ms {pct:>10.1f}%")
        print(f"  {'-' * 24} {'-' * 10} {'-' * 12}")
        tms = total * 1e3
        tpct = total / self.baseline_s * 100 if self.baseline_s > 0 else 0
        print(f"  {'SUM':<24} {tms:>8.3f}ms {tpct:>10.1f}%")
        print(
            f"\n  (SUM > 100% means tasks overlap on the critical path;\n"
            f"   SUM < 100% means some wall-clock time is framework overhead)"
        )


class TaskProfiler:
    """Measure per-task **exposed time** for auto-scheduling.

    Delegates to :meth:`SWPipeline.enable_shortcut` /
    :meth:`SWPipeline.disable_shortcut` and
    :meth:`SWPipeline.run_one_serial_iter`, so the shortcut logic
    (caching, autograd-safe restore, sequencer advancement for
    globally-ordered tasks) is shared with runtime shortcutting.

    ::

        exposed_time(T) = baseline_serial - serial_with_T_shortcut

    Example::

        profiler = TaskProfiler(pipe)
        result = profiler.profile(batches, num_warmup=3, num_measure=10)
        result.print_report()
    """

    def __init__(self, pipeline: SWPipeline) -> None:
        self._pipe = pipeline

    def _timed_run(self, batch: Any, count: int) -> float:
        """Run *count* serial iterations with the same *batch*.

        Returns average wall-clock seconds per iteration.  Only two
        ``cuda.synchronize`` calls total (before and after).
        """
        pipe = self._pipe
        dev = pipe.device
        torch.cuda.synchronize(dev)
        t0 = time.perf_counter()
        for i in range(count):
            pipe.run_one_serial_iter(batch, i)
        torch.cuda.synchronize(dev)
        return (time.perf_counter() - t0) / count

    def profile(
        self,
        batch: Any,
        num_warmup: int = 3,
        num_measure: int = 10,
        num_rounds: int = 3,
    ) -> ProfileResult:
        """Profile exposed time for each task using a single representative batch.

        Four phases:

        1. **Warmup** — ``num_warmup`` normal serial iterations.
        2. **Baseline** — ``num_rounds`` rounds × ``num_measure``
           iterations; take median of per-round averages.
        3. **Per-task shortcut** — for each task *T*:

           a. ``enable_shortcut(T)`` + one caching iteration.
           b. ``num_rounds`` rounds × ``num_measure`` timed iterations.
           c. ``disable_shortcut(T)`` to restore normal mode.

        4. Compute ``exposed(T) = max(0, baseline - median_shortcut(T))``.

        Args:
            batch: a single batch (same format as ``next(data_iter)``).
            num_warmup: warmup iterations (not timed).
            num_measure: iterations per timed round.
            num_rounds: number of rounds (median of round-averages is taken).

        Returns:
            :class:`ProfileResult` with baseline and per-task exposed times.
        """
        import statistics

        pipe = self._pipe

        for _ in range(num_warmup):
            pipe.run_one_serial_iter(batch, 0)

        base_avgs = [self._timed_run(batch, num_measure) for _ in range(num_rounds)]
        baseline = statistics.median(base_avgs)

        exposed: Dict[str, float] = {}
        for td in pipe._topo_order:
            pipe.enable_shortcut(td.name)
            pipe.run_one_serial_iter(batch, 0)  # caching iteration

            round_avgs = [
                self._timed_run(batch, num_measure) for _ in range(num_rounds)
            ]
            exposed[td.name] = max(0.0, baseline - statistics.median(round_avgs))

            pipe.disable_shortcut(td.name)

        return ProfileResult(baseline_s=baseline, exposed_s=exposed)

    def profile_many(
        self,
        batches: list,
        num_warmup: int = 3,
        num_measure: int = 10,
        num_rounds: int = 3,
    ) -> List[ProfileResult]:
        """Profile each batch independently, return one result per batch.

        Useful for understanding how exposed time varies across different
        data distributions or batch sizes.
        """
        return [
            self.profile(
                b, num_warmup=num_warmup, num_measure=num_measure, num_rounds=num_rounds
            )
            for b in batches
        ]
